sudo: enabled
dist: bionic
git:
  submodules: false
before_install:
  - sudo apt-get update -qq
  - git submodule update --init --remote --recursive
  - sudo apt-get install -y autoconf bison build-essential flex gettext gtk-doc-tools libev-dev libgcrypt-dev libglib2.0-dev libgnutls28-dev libicu-dev liblua5.1-dev libmysqlclient-dev libpcre3-dev libpq-dev libsqlite3-dev libtool libwrap0-dev libxml2-dev lua5.1 perl pkg-config python-babel python-cheetah python-dateutil python-dev python-lesscpy python-netaddr python-twisted-names python-tz ruby-dev swig t1-xfree86-nonfree
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libruby-2.5.so /usr/lib/libruby.so
  - sudo ldconfig
  - sudo mkdir -p /usr/include/libev
  - sudo cp /usr/include/ev++.h /usr/include/ev.h /usr/include/libev/
language: c
script: 
- cd libprelude && for i in ../patchs/libprelude-5.1.0-*.patch; do patch -p1 < $i; done && sh autogen.sh && ./configure --enable-gtk-doc && make && make distcheck && sudo make install && sudo ldconfig
- cd ../libpreludedb && for i in ../patchs/libpreludedb-5.1.0-*.patch; do patch -p1 < $i; done && sh autogen.sh && ./configure --enable-gtk-doc && make && make distcheck && sudo make install && sudo ldconfig
- cd ../prelude-manager && sh autogen.sh && ./configure --enable-gtk-doc && make && make distcheck && sudo make install
- cd ../prelude-lml && sh autogen.sh && ./configure --enable-gtk-doc && make && make distcheck && sudo make install
- cd ../prelude-correlator && python setup.py sdist && sudo python setup.py install
- cd ../prewikka && python setup.py sdist && sudo python setup.py install
notifications:
   irc: "irc.freenode.net#prelude"
